name: "Test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  dependabot:
    name: "Dependabot"
    needs: [test]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
