name: "Test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      REDIS_PASS: ${{ secrets.REDIS_PASS }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint:fix
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
