name: "Test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Bundle
        run: npm run bundle
      - name: Test
        run: npm run test
